server: true
page_title: "##feminism"
title: "##feminism"
tagline: Freenode Feminists
repository_url: https://github.com/freenode-feminists/freenode-feminists.github.com/
permalink: pretty
markdown: kramdown
