server: true
page_title: "##feminism"
title: "##feminism"
tagline: Freenode Feminists
repository_url: https://github.com/freenode-feminism/freenode-feminism.github.io/
permalink: pretty
markdown: kramdown
